# Servidor
server.port=${PORT:8080}
server.address=${HOST:0.0.0.0}

# Base de Datos
spring.datasource.url=jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:db}
spring.datasource.username=${DATABASE_USER:admin}
spring.datasource.password=${DATABASE_PASSWORD:password}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# RFC 7807
spring.mvc.problemdetails.enabled=false

# Jackson - Disable float to int coercion
spring.jackson.deserialization.accept-float-as-int=false
